{{- if .Values.nfsbroker.enabled }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: nfsbroker-credentials
stringData:
  USERNAME: nfsbroker
  PASSWORD: nfsbroker
  UAA_CLIENT_ID: "nfsbroker-credhub-client"
  UAA_CLIENT_SECRET: {{ .Values.nfsbroker.oauthClientsSecret | quote }}
{{- end }}
