name: uaa
# renovate: dataSource=github-releases depName=cloudfoundry/uaa-release
version: 0.21.0
description: A Helm chart for UAA
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/uaa-release
appVersion: 78.14.0
