certificateSecret: ""
hostname: "uaa.127-0-0-1.nip.io"
address: "https://uaa.127-0-0-1.nip.io"
loginAddress: "https://login.127-0-0-1.nip.io"

image:
  repository: ghcr.io/cloudfoundry/k8s/uaa
  tag: ""
  imagePullPolicy: IfNotPresent

nodeSelector: ~
tolerations: ~

uaaAdminSecret: ~
oauthClientsSecret: ~
uaadb:
  name: uaa
  password: ~
  user: postgres
  port: 5432
  address: postgresql.{{ .Release.Namespace }}.svc.cluster.local
  caCertificateSecret: ""
  skipSSLVerify: true

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # renovate: dataSource=github-releases depName=cloudfoundry/routing-release
    tag: "0.387.0"
    imagePullPolicy: IfNotPresent
  resources: ~

scim:
  users:
    - name: ccadmin
      password: "changeme"
      email: ccadmin
      firstName: ""
      lastName: ""
      groups: clients.read,cloud_controller.admin,doppler.firehose,network.admin,openid,routing.router_groups.read,routing.router_groups.write,scim.read,scim.write
      origin: uaa

oauth:
  clients:
    cc-service-dashboards:
      authorities: clients.read,clients.write,clients.admin
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      scope: openid,cloud_controller_service_permissions.read
      id: cc-service-dashboards
    cc_routing:
      authorities: routing.router_groups.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: cc_routing
    cc_service_key_client:
      authorities: credhub.read,credhub.write
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: cc_service_key_client
    cf:
      access-token-validity: 1200
      authorities: uaa.none
      authorized-grant-types: password,refresh_token,urn:ietf:params:oauth:grant-type:jwt-bearer
      override: true
      refresh-token-validity: 2592000
      secret: ''
      scope: network.admin,network.write,cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user,routing.router_groups.read,routing.router_groups.write,cloud_controller.admin_read_only,cloud_controller.global_auditor,perm.admin,clients.read
      id: cf
    cf_smoke_tests:
      authorities: cloud_controller.admin,clients.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: cf_smoke_tests
    cloud_controller_username_lookup:
      authorities: scim.userids,scim.read
      authorized-grant-types: client_credentials
      override: true
      secret: "{{ .Values.oauthClientsSecret }}"
      id: cloud_controller_username_lookup
    credhub_admin_client:
      authorities: credhub.read,credhub.write
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: credhub_admin_client
    doppler:
      authorities: uaa.resource
      authorized-grant-types: client_credentials
      override: true
      secret: "{{ .Values.oauthClientsSecret }}"
      id: doppler
    gorouter:
      authorities: routing.routes.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: gorouter
    network-policy:
      authorities: uaa.resource,cloud_controller.admin_read_only
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: network-policy
    routing_api_client:
      authorities: routing.routes.write,routing.routes.read,routing.router_groups.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: routing_api_client
    ssh-proxy:
      authorized-grant-types: authorization_code
      autoapprove: true
      override: true
      redirect-uri: "{{ .Values.address }}/login"
      secret: "{{ .Values.oauthClientsSecret }}"
      scope: openid,cloud_controller.read,cloud_controller.write,cloud_controller.admin
      id: ssh-proxy
    tcp_emitter:
      authorities: routing.routes.write,routing.routes.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: tcp_emitter
    tcp_router:
      authorities: routing.routes.read,routing.router_groups.read
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"
      id: tcp_router
    admin:
      authorized-grant-types: client_credentials
      authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
      id: admin
      secret: "{{ .Values.oauthClientsSecret }}"
    nfsbroker-credhub-client:
      authorities: credhub.read,credhub.write
      authorized-grant-types: client_credentials
      secret: "{{ .Values.oauthClientsSecret }}"

uaaConfigOverrides: {}
