name: routing
# renovate: dataSource=github-releases depName=cloudfoundry/routing-release
version: 0.386.0
description: Helm chart for Gorouter components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/routing-release
appVersion: 0.386.0
