name: loggregator
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-release
version: 107.0.30
description: Helm chart for Loggregator components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-release
