name: loggregator
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-release
version: 0.16.0
description: Helm chart for Loggregator components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-release
appVersion: 107.0.29
