systemDomain: "cf.127-0-0-1.nip.io"

loggregator:
  enabled: false

doppler:
  certificateSecret: ""
  resources: ~
  image:
    repository: ghcr.io/cloudfoundry/k8s/doppler
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

reverseLogProxy:
  certificateSecret: ""
  resources: ~
  image:
    repository: ghcr.io/cloudfoundry/k8s/reverse-log-proxy
    tag: ""
    imagePullPolicy: IfNotPresent

reverseLogProxyGateway:
  certificateSecret: ""
  resources: ~
  image:
    repository: ghcr.io/cloudfoundry/k8s/reverse-log-proxy-gateway
    tag: ""
    imagePullPolicy: IfNotPresent

trafficcontroller:
  certificateSecret: ""
  resources: ~
  image:
    repository: ghcr.io/cloudfoundry/k8s/traffic-controller
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

oauthClientsSecret: ~

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # renovate: dataSource=github-releases depName=cloudfoundry/routing-release
    tag: "0.387.0"
    imagePullPolicy: IfNotPresent
  resources: ~