{{ if .Values.cloudController.enabled }}
{{ $_ := required ".Values.ccdb.password must be provided" .Values.ccdb.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cc-shared
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
stringData:
  DB: {{ .Values.ccdb.name }}
  DB_CONNECTION_STRING: postgres://{{ .Values.ccdb.user }}:{{ .Values.ccdb.password }}@{{ tpl .Values.ccdb.address . }}:{{ .Values.ccdb.port }}/{{ .Values.ccdb.name }}
  CLOUD_CONTROLLER_NG_CONFIG: /etc/cloud-controller/config.yaml
  RAILS_ENV: production
{{- end }}
