ccDeploymentUpdater:
  resources: ~
  nodeSelector: ~
  tolerations: ~

ccWorker:
  resources: ~
  nodeSelector: ~
  tolerations: ~

ccUploader:
  resources: ~
  certificateSecret: ""
  hostname: "cc-uploader.{{ .Release.Namespace }}.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-uploader
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

ccWorkerClock:
  resources: ~
  nodeSelector: ~
  tolerations: ~

cloudController:
  enabled: false
  resources: ~
  certificateSecret: ""
  appDomain: apps.127-0-0-1.nip.io
  externalDomain: api.127-0-0-1.nip.io
  internalDomain: cloud-controller.{{ .Release.Namespace }}.svc.cluster.local
  internalServiceHostname: cloud-controller.{{ .Release.Namespace }}.svc.cluster.local
  systemDomain: 127-0-0-1.nip.io
  systemDomainOrganization: system
  appSSHEndpoint: ssh.127-0-0-1.nip.io:2222
  sshProxyKeyFingerprint: ""
  loginUrl: https://login.127-0-0-1.nip.io
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ""
    imagePullPolicy: IfNotPresent
  loggregator:
    endpoint: "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local:3458"
    subjectName: metron
  doppler:
    url: wss://doppler.127-0-0-1.nip.io:443
  logCache:
    url: https://log-cache.127-0-0-1.nip.io
  logStream:
    url: https://log-stream.127-0-0-1.nip.io
  uaa:
    url: https://uaa.127-0-0-1.nip.io
  blobstore:
    type: storage-cli
    provider: s3
    resource_directory_key: cc-resources
    app_package_directory_key: cc-packages
    droplet_directory_key: cc-droplets
    buildpack_directory_key: cc-buildpacks
    storage_cli:
      host: http://blobstore.127-0-0-1.nip.io
      region: us-east-1
      aws_access_key_id: admin
      aws_secret_access_key: ~
    fog_connection:
      provider: ~
  diego:
    fileServerUrl: http://fileserver.{{ .Release.Namespace }}.svc.cluster.local:8080
    ccUploaderUrl: https://cc-uploader.{{ .Release.Namespace }}.svc.cluster.local:9091
  credhubApi:
    internalUrl: https://credhub.{{ .Release.Namespace }}.svc.cluster.local:8844
    externalUrl: ""
  nats:
    address: nats.{{ .Release.Namespace }}.svc.cluster.local:4222
  nodeSelector: ~
  tolerations: ~
  enableCommaDelimitedDestinations: false
  stacks:
  - description: Cloud Foundry Linux-based filesystem (Ubuntu 22.04)
    name: cflinuxfs4
  default_stack: cflinuxfs4
  lifecycle_bundles:
    buildpack/cflinuxfs4: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
    cnb/cflinuxfs4: cnb_app_lifecycle/cnb_app_lifecycle.tgz
    docker: docker_app_lifecycle/docker_app_lifecycle.tgz
  droplet_destinations:
    cflinuxfs4: /home/vcap
  docker_staging_stack: cflinuxfs4
  securityGroupDefinitions:
    - name: "public_networks"
      rules:
        - destination: "0.0.0.0-9.255.255.255"
          protocol: "all"
        - destination: "11.0.0.0-169.253.255.255"
          protocol: "all"
        - destination: "169.255.0.0-172.15.255.255"
          protocol: "all"
        - destination: "172.32.0.0-192.167.255.255"
          protocol: "all"
        - destination: "192.169.0.0-255.255.255.255"
          protocol: "all"
    - name: "dns"
      rules:
        - destination: "0.0.0.0/0"
          ports: "53"
          protocol: "tcp"
        - destination: "0.0.0.0/0"
          ports: "53"
          protocol: "udp"
  defaultStagingSecurityGroups:
    - "public_networks"
    - "dns"
  defaultRunningSecurityGroups:
    - "public_networks"
    - "dns"
  
localWorker:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ""
    imagePullPolicy: IfNotPresent
  resources: ~

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # renovate: dataSource=github-releases depName=cloudfoundry/routing-release
    tag: "0.387.0"
    imagePullPolicy: IfNotPresent
  resources: ~

nginx:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-nginx
    tag: ""
    imagePullPolicy: IfNotPresent
  resources: ~

tpsWatcher:
  enabled: false
  resources: ~
  certificateSecret: ""
  hostname: tps.{{ .Release.Namespace }}.svc.cluster.local
  image:
    repository: ghcr.io/cloudfoundry/k8s/tps-watcher
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

ccdb:
  name: cc
  password: ~
  user: postgres
  port: 5432
  address: postgresql.{{ .Release.Namespace }}.svc.cluster.local
  caCertificateSecret: ""
  skipSSLVerify: true
  skipHostnameVerify: false

oauthClientsSecret: ~
