resources:
  - all.yaml
images:
  - name: ghcr.io/cloudfoundry/k8s/auctioneer
    newName: auctioneer
  - name: ghcr.io/cloudfoundry/k8s/bbs
    newName: bbs
  - name: ghcr.io/cloudfoundry/k8s/locket
    newName: locket
  - name: ghcr.io/cloudfoundry/k8s/ssh-proxy
    newName: ssh-proxy
  - name: ghcr.io/cloudfoundry/k8s/route-emitter
    newName: route-emitter
  - name: ghcr.io/cloudfoundry/k8s/fileserver
    newName: fileserver
