name: cf-networking
# renovate: dataSource=github-releases depName=cloudfoundry/cf-networking-release
version: 3.112.1
description: Helm chart for CF Networking components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/cf-networking-release
appVersion: 3.112.1
