name: log-cache
# renovate: dataSource=github-releases depName=cloudfoundry/log-cache-release
version: 3.2.10
description: Helm chart for Log Cache components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/log-cache-release
appVersion: 3.2.10
