---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logcache-route-registrar-config
data:
  route-registrar.json: |-
    {
      "message_bus_servers": [
        {
          "host": "{{ tpl .Values.logCacheApi.nats.address . }}"
        }
      ],
      "nats_mtls_config": {
        "enabled": true,
        "cert_path": "/etc/ssl/certs/log-cache-api/tls.crt",
        "key_path": "/etc/ssl/certs/log-cache-api/tls.key",
        "ca_path": "/etc/ssl/certs/log-cache-api/ca.crt"
      },
      "host": "",
      "routes": [
        {
          "name": "log-cache-api",
          "port": 8083,
          "registration_interval": "10s",
          "server_cert_domain_san": "{{ .Values.logCacheApi.hostname }}",
          "tags": {
            "component": "LogCache"
          },
          "uris": [
            "{{ .Values.logCacheApi.hostname }}"
          ]
        }
      ]
    }