name: loggregator-agent
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-agent-release
version: 8.3.22
description: Helm chart for Loggregator Agent components
type: application
apiVersion: v2
# renovate: dataSource=github-releases depName=cloudfoundry/loggregator-agent-release
appVersion: 8.3.22
