name: Init
description: Common setup steps

runs:
  using: "composite"
  steps:
    - name: retrieve secret from Vault
      id: vault
      uses: hashicorp/vault-action@v3
      with:
        method: jwt
        url: https://vault.tools.sap/
        namespace: scp/teams/cki
        role: actions
        secrets: |
          jenkins/data/GITHUB_COM token | GH_COM_TOKEN ;
    - name: checkout kind-deployment
      uses: actions/checkout@v6
      with:
        github-server-url: https://github.com
        repository: cloudfoundry/kind-deployment
        ref: main
        path: kind
        token: ${{ steps.vault.outputs.GH_COM_TOKEN }}
    - uses: docker/setup-buildx-action@v4
      with:
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["dockerio.int.repositories.cloud.sap"]
    - name: Set kernel settings
      shell: bash
      run: |
        docker run --rm \
          --privileged \
          --pid host \
          alpine sh -c "sysctl -w fs.inotify.max_user_instances=512"
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - uses: azure/setup-helm@v5
    - name: Install dependencies
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin && echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        curl -L https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64 -o $HOME/.local/bin/kind
        chmod +x $HOME/.local/bin/kind
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}&source=github" | tar -zx
        mv cf8 $HOME/.local/bin/cf
        curl -L https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz | tar -xz -C $HOME/.local/bin helmfile
      env:
        # renovate: dataSource=github-releases depName=cloudfoundry/cli
        CF_CLI_VERSION: "8.18.3"
        # renovate: dataSource=github-releases depName=kubernetes-sigs/kind
        KIND_VERSION: "0.31.0"
        # renovate: dataSource=github-releases depName=helmfile/helmfile
        HELMFILE_VERSION: "1.5.1"
    - name: helmfile init
      shell: bash
      run: |
        helm plugin install ./plugin
        helmfile init --force
