name: Release Binary Buildpack

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "binary-buildpack/docker-bake.hcl"

jobs:
  delete-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Delete package version
        run: |
          # gh api --method DELETE /orgs/cloudfoundry/packages/container/cloud-controller
          gh api --method DELETE /orgs/cloudfoundry/packages/container/cc-uploader
          gh api --method DELETE /orgs/cloudfoundry/packages/container/tps-watcher
          gh api --method DELETE /orgs/cloudfoundry/packages/container/cc-nginx
