name: Release Binary Buildpack

on:
  push:
    branches:
      - main
    paths:
      - 'binary-buildpack/docker-bake.hcl'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/


jobs:
  binary-buildpack-release:
    runs-on: [self-hosted, solinas]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Determine Versions
        working-directory: binary-buildpack
        run: |
          echo "VERSION=$(docker buildx bake --print | jq -r '.target | to_entries[] | .value.tags[]' | grep -v ':latest$' | head -n1 | awk -F: '{print $NF}')" >> $GITHUB_ENV
      - name: Release Images
        working-directory: binary-buildpack
        run: |
          # Check if image available
          if docker pull $REGISTRY_PREFIX/binary-buildpack:$VERSION > /dev/null 2>&1; then
             echo "binary-buildpack image already exists in version $VERSION."
          else
            docker buildx bake #--push
          fi
