name: Release CAPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "capi/helm/Chart.yaml"

jobs:
  capi-image-release:
    uses: ./.github/workflows/reusable-matrix-image-build.yaml
    with:
      target: capi
  capi-helm-release:
    needs: capi-image-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm Chart
        working-directory: capi
        env:
          REGISTRY_PREFIX: ghcr.io/cloudfoundry/
          TARGET: capi
        run: |
          VERSION=$(yq e '.version' helm/Chart.yaml)
          HELM_REGISTRY="${REGISTRY_PREFIX}helm"
          IMAGE="${HELM_REGISTRY}/${TARGET}:${VERSION}"

          if docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
             echo "Helm chart already exists in version $VERSION."
          else
            helm package ./helm -d ${{ runner.temp }}
            helm push ${{ runner.temp }}/capi-*.tgz oci://${HELM_REGISTRY}
          fi
