name: Verify CF-Networking

on:
  pull_request:
    branches:
      - main

jobs:
  cf-networking-verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: check changes
        uses: dorny/paths-filter@v4
        id: check
        with:
          filters: |
            should_run:
              - 'cf-networking/**'
              - '.github/workflows/cf-networking-verify.yaml'
              - '.github/actions/**'
      - uses: ./.github/actions/init
        if: steps.check.outputs.should_run == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: cf-networking
        if: steps.check.outputs.should_run == 'true'
        run: |
          echo "ROUTING_RELEASE_VERSION=$(yq -r '.routeRegistrar.image.tag' helm/values.yaml)" >> $GITHUB_ENV
          echo "BOSH_DNS_RELEASE_VERSION=$(yq -r '.boshDns.image.tag' helm/values.yaml)" >> $GITHUB_ENV
      - name: Build cf-networking images
        if: steps.check.outputs.should_run == 'true'
        working-directory: cf-networking
        run: docker buildx bake --load
      - name: Build route-registrar image
        if: steps.check.outputs.should_run == 'true'
        working-directory: routing
        run: docker buildx bake route-registrar --load
      - name: Build bosh-dns image
        if: steps.check.outputs.should_run == 'true'
        working-directory: bosh-dns
        run: docker buildx bake bosh-dns --load
      - name: Create KinD Cluster
        if: steps.check.outputs.should_run == 'true'
        run: make -C kind create-kind init
      - name: Load cf-networking images into KinD
        if: steps.check.outputs.should_run == 'true'
        working-directory: cf-networking
        run: |
          for image in $(docker buildx bake --print | jq -c -r '.target[].tags | join(" ")'); do
            kind load docker-image --name cfk8s ${image}
          done
      - name: Load route-registrar image into KinD
        if: steps.check.outputs.should_run == 'true'
        working-directory: routing
        run: |
          for image in $(docker buildx bake route-registrar --print | jq -c -r '.target[].tags | join(" ")'); do
            kind load docker-image --name cfk8s ${image}
          done
      - name: Load bosh-dns image into KinD
        if: steps.check.outputs.should_run == 'true'
        working-directory: bosh-dns
        run: |
          for image in $(docker buildx bake bosh-dns --print | jq -c -r '.target[].tags | join(" ")'); do
            kind load docker-image --name cfk8s ${image}
          done
      - name: Use images
        if: steps.check.outputs.should_run == 'true'
        working-directory:  cf-networking
        run: |
          yq -e -i '.policyServer.image.repository = "policy-server"' helm/values.yaml
          yq -e -i '.serviceDiscoveryController.image.repository = "service-discovery-controller"' helm/values.yaml
          yq -e -i '.boshDnsAdapter.image.repository = "bosh-dns-adapter"' helm/values.yaml
          yq -e -i '.routeRegistrar.image.repository = "route-registrar"' helm/values.yaml
          yq -e -i '.boshDns.image.repository = "bosh-dns"' helm/values.yaml
      - name: Deploy
        if: steps.check.outputs.should_run == 'true'
        run: |
          kind get kubeconfig --name cfk8s > kind/temp/kubeconfig
          docker run --rm --net=host --env-file kind/temp/secrets.env \
            -v "${{ github.workspace }}/kind/temp/certs:/certs" \
            -v "${{ github.workspace }}:/wd" \
            -e KUBECONFIG=/wd/kind/temp/kubeconfig \
            --workdir /wd ghcr.io/helmfile/helmfile:$HELMFILE_VERSION \
            helmfile sync -f kind/helmfile.yaml.gotmpl --state-values-set charts.cfNetworking.url=../cf-networking/helm
        env:
          # renovate: dataSource=docker packageName=ghcr.io/helmfile/helmfile depName=helmfile/helmfile
          HELMFILE_VERSION: "v1.5.1"