name: Release cf-networking

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cf-networking/helm/Chart.yaml'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/
  HELM_REGISTRY_PREFIX: ghcr.io/cloudfoundry/helm/


jobs:
  cf-networking-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: cf-networking
        run: |
          echo "CHART_VERSION=$(yq e '.version' helm/Chart.yaml)" >> $GITHUB_ENV
          echo "APP_VERSION=$(yq e '.appVersion' helm/Chart.yaml)" >> $GITHUB_ENV
      - name: Release Images
        working-directory: cf-networking
        run: |
          # Check if image available
          if docker manifest inspect ${REGISTRY_PREFIX}policy-server:$APP_VERSION > /dev/null 2>&1; then
             echo "policy-server image already exists in version $APP_VERSION."
          else
            docker buildx bake --set '*.platform=linux/amd64,linux/arm64' --push
          fi
      - name: Publish Helm Chart
        working-directory: cf-networking
        run: |
          # Check if chart available
          if helm show chart oci://${HELM_REGISTRY_PREFIX}cf-networking --version $CHART_VERSION > /dev/null 2>&1; then
             echo "Helm chart already exists in version $CHART_VERSION."
          else
            helm package ./helm -d ${{ runner.temp }}
            helm push ${{ runner.temp }}/cf-networking-*.tgz oci://${HELM_REGISTRY_PREFIX}
          fi
