name: Verify cflinuxfs5

on:
  pull_request:
    branches:
      - main

env:
  BUILDX_BAKE_ENTITLEMENTS_FS: "0"

jobs:
  cflinuxfs5-verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: check changes
        uses: dorny/paths-filter@v4
        id: check
        with:
          filters: |
            should_run:
              - 'cflinuxfs5/**'
              - 'stacks.Dockerfile'
              - '.github/workflows/cflinuxfs5-verify.yaml'
              - '.github/actions/**'
      - uses: ./.github/actions/init
        if: steps.check.outputs.should_run == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Images
        if: steps.check.outputs.should_run == 'true'
        working-directory: cflinuxfs5
        run: docker buildx bake --load
      - name: Use image
        if: steps.check.outputs.should_run == 'true'
        run: |
          cat >> ${{ github.workspace }}/state-values.yaml <<EOF
          stacks:
            cflinuxfs5:
              image: cflinuxfs5:latest
          EOF
      - uses: cloudfoundry/kind-deployment/.github/actions/setup-cf@load-images
        if: steps.check.outputs.should_run == 'true'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          load-images: "cflinuxfs5"
          additional-values-files: "${{ github.workspace }}/state-values.yaml"
      - uses: cloudfoundry/kind-deployment/.github/actions/setup-cf-tests@v0.25.0
        if: steps.check.outputs.should_run == 'true'
        with:
          test-repo: cf-smoke-tests
          test-branch: main
          config-template: ${{ github.workspace }}/kind-deployment/.github/smoke-config.tpl
          config-output: ${{ github.workspace }}/.github/smoke-config.json
      - name: run smoke test
        if: steps.check.outputs.should_run == 'true'
        env:
          CONFIG: "${{ github.workspace }}/.github/smoke-config.json"
          GINKGO_NO_COLOR: "true"
        run: |
          ./cf-smoke-tests/bin/test --no-color --github-output --timeout=30m --procs=4 --json-report report.json
