name: Diego Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_PREFIX: europe-west3-docker.pkg.dev/sap-se-gcp-istio-dev/public/cf/

jobs:
  create-landscape:
    runs-on: [self-hosted, solinas]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: ./.github/actions/init
      - name: Build Images
        if: steps.check_changes.outputs.skip != 'true'
        run: docker buildx bake diego
      - name: Create KinD Cluster
        run: make -C kind create-kind init
