name: Release Java Buildpack

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'java-buildpack/docker-bake.hcl'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/
  BUILDX_BAKE_ENTITLEMENTS_FS: "0"

jobs:
  java-buildpack-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: java-buildpack
        run: |
          echo "VERSION=$(docker buildx bake --print | jq -r '.target | to_entries[] | .value.tags[]' | grep -v ':latest$' | head -n1 | awk -F: '{print $NF}')" >> $GITHUB_ENV
      - name: Release Images
        working-directory: java-buildpack
        run: |
          # Check if image available
          if docker pull ${REGISTRY_PREFIX}java-buildpack:$VERSION > /dev/null 2>&1; then
             echo "java-buildpack image already exists in version $VERSION."
          else
            docker buildx bake --set '*.platform=linux/amd64,linux/arm64' --push
          fi
