name: Verify Log Cache

on:
  pull_request:
    branches:
      - main

jobs:
  log-cache-verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: check changes
        uses: dorny/paths-filter@v4
        id: check
        with:
          filters: |
            should_run:
              - 'log-cache/**'
              - '.github/workflows/log-cache-verify.yaml'
              - '.github/actions/**'
      - uses: ./.github/actions/init
        if: steps.check.outputs.should_run == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build logcache images
        if: steps.check.outputs.should_run == 'true'
        working-directory: log-cache
        run: docker buildx bake --load
      - name: Build route-registrar image
        if: steps.check.outputs.should_run == 'true'
        working-directory: routing
        run: docker buildx bake route-registrar --load
      - name: Create KinD Cluster
        if: steps.check.outputs.should_run == 'true'
        run: make -C kind create-kind init
      - name: Load Images into KinD
        if: steps.check.outputs.should_run == 'true'
        working-directory: log-cache
        run: |
          for image in $(docker buildx bake --print | jq -c -r '.target[].tags | join(" ")'); do
            kind load docker-image --name cfk8s ${image}
          done
      - name: Load route-registrar image into KinD
        if: steps.check.outputs.should_run == 'true'
        working-directory: routing
        run: |
          for image in $(docker buildx bake route-registrar --print | jq -c -r '.target[].tags | join(" ")'); do
            kind load docker-image --name cfk8s ${image}
          done
      - name: Use Images
        if: steps.check.outputs.should_run == 'true'
        working-directory:  log-cache
        run: |
          yq -e -i '.logCacheApi.cfAuthProxy.image.repository = "cf-auth-proxy"' helm/values.yaml
          yq -e -i '.logCacheApi.gateway.image.repository = "gateway"' helm/values.yaml
          yq -e -i '.logCacheBackend.syslogServer.image.repository = "syslog-server"' helm/values.yaml
          yq -e -i '.logCacheBackend.logCache.image.repository = "log-cache"' helm/values.yaml
          yq -e -i '.routeRegistrar.image.repository = "route-registrar"' helm/values.yaml
      - name: Deploy
        if: steps.check.outputs.should_run == 'true'
        run: |
          kind get kubeconfig --name cfk8s > kind/temp/kubeconfig
          docker run --rm --net=host --env-file kind/temp/secrets.env \
            -v "${{ github.workspace }}/kind/temp/certs:/certs" \
            -v "${{ github.workspace }}:/wd" \
            -e KUBECONFIG=/wd/kind/temp/kubeconfig \
            --workdir /wd ghcr.io/helmfile/helmfile:v$HELMFILE_VERSION \
            helmfile sync -f kind/helmfile.yaml.gotmpl --state-values-set charts.logCache.url=../log-cache/helm
        env:
          # renovate: dataSource=docker depName=helmfile/helmfile packageName=ghcr.io/helmfile/helmfile
          HELMFILE_VERSION: "1.7.1"
