name: Release loggregator

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'loggregator/helm/Chart.yaml'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/
  HELM_REGISTRY_PREFIX: ghcr.io/cloudfoundry/helm/


jobs:
  loggregator-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: loggregator
        run: |
          echo "CHART_VERSION=$(cat helm/Chart.yaml | yq e '.version')" >> $GITHUB_ENV
          echo "APP_VERSION=$(cat helm/Chart.yaml | yq e '.appVersion')" >> $GITHUB_ENV
      - name: Release Images
        working-directory: loggregator
        run: |
          # Check if image available
          if docker pull ${REGISTRY_PREFIX}doppler:$APP_VERSION > /dev/null 2>&1; then
             echo "doppler image already exists in version $APP_VERSION."
          else
            docker buildx bake --set '*.platform=linux/amd64,linux/arm64' --push
          fi
      - name: Publish Helm Chart
        working-directory: loggregator
        run: |
          # Check if chart available
          if helm show chart oci://${HELM_REGISTRY_PREFIX}loggregator --version $CHART_VERSION > /dev/null 2>&1; then
             echo "Helm chart already exists in version $CHART_VERSION."
          else
            helm package ./helm -d ${{ runner.temp }}
            helm push ${{ runner.temp }}/loggregator-*.tgz oci://${HELM_REGISTRY_PREFIX}
          fi
