name: Release nfs-volume

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nfs-volume/helm/Chart.yaml'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/
  HELM_REGISTRY_PREFIX: ghcr.io/cloudfoundry/helm/


jobs:
  nfs-volume-image-release:
    uses: ./.github/workflows/reusable-matrix-image-build.yaml
    with:
      target: nfs-volume
  nfs-volume-helm-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm Chart
        working-directory: nfs-volume
        run: |
          CHART_VERSION=$(yq e '.version' helm/Chart.yaml)
          APP_VERSION=$(yq e '.appVersion' helm/Chart.yaml)

          # Check if chart available
          if helm show chart oci://${HELM_REGISTRY_PREFIX}nfs-volume --version $CHART_VERSION > /dev/null 2>&1; then
             echo "Helm chart already exists in version $CHART_VERSION."
          else
            helm package ./helm -d ${{ runner.temp }}
            helm push ${{ runner.temp }}/nfs-volume-*.tgz oci://${HELM_REGISTRY_PREFIX}
          fi
