name: Release Staticfile Buildpack

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'staticfile-buildpack/docker-bake.hcl'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/


jobs:
  staticfile-buildpack-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: staticfile-buildpack
        run: |
          echo "VERSION=$(docker buildx bake --print | jq -r '.target | to_entries[] | .value.tags[]' | grep -v ':latest$' | head -n1 | awk -F: '{print $NF}')" >> $GITHUB_ENV
      - name: Release Images
        working-directory: staticfile-buildpack
        run: |
          # Check if image available
          if docker pull ${REGISTRY_PREFIX}staticfile-buildpack:$VERSION > /dev/null 2>&1; then
             echo "staticfile-buildpack image already exists in version $VERSION."
          else
            docker buildx bake --set '*.platform=linux/amd64,linux/arm64' --push
          fi
