name: Verify Staticfile Buildpack

on:
  pull_request:
    branches:
      - main

env:
  BUILDX_BAKE_ENTITLEMENTS_FS: "0"

jobs:
  staticfile-buildpack-verify:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: check changes
        uses: dorny/paths-filter@v4
        id: check
        with:
          filters: |
            should_run:
              - 'staticfile-buildpack/**'
              - '.github/workflows/staticfile-buildpack-verify.yaml'
              - '.github/actions/**'
      - uses: ./.github/actions/init
        if: steps.check.outputs.should_run == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Images
        if: steps.check.outputs.should_run == 'true'
        working-directory: staticfile-buildpack
        run: docker buildx bake --load
