name: Release UAA

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'uaa/helm/Chart.yaml'
      
env:
  REGISTRY_PREFIX: ghcr.io/cloudfoundry/k8s/
  HELM_REGISTRY_PREFIX: ghcr.io/cloudfoundry/helm/


jobs:
  uaa-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Versions
        working-directory: uaa
        run: |
          echo "VERSION=$(cat helm/Chart.yaml | yq e '.version')" >> $GITHUB_ENV
      - name: Release Images
        working-directory: uaa
        run: |
          # Check if image available
          if docker pull $REGISTRY_PREFIX/uaa:$VERSION > /dev/null 2>&1; then
             echo "uaa image already exists in version $VERSION."
          else
            docker buildx bake --set '*.platform=linux/amd64,linux/arm64' --push
          fi
      - name: Publish Helm Chart
        working-directory: uaa
        run: |
          # Check if chart available
          if helm show chart oci://$HELM_REGISTRY_PREFIX/uaa --version $VERSION > /dev/null 2>&1; then
             echo "Helm chart already exists in version $VERSION."
          else
            helm package ./helm -d ${{ runner.temp }}
            helm push ${{ runner.temp }}/uaa-*.tgz oci://$HELM_REGISTRY_PREFIX/
          fi
