---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-route-registrar-config
data:
  route-registrar.json: |-
    {
      "message_bus_servers": [
        {
          "host": "nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        }
      ],
      "nats_mtls_config": {
        "enabled": true,
        "cert_path": "/etc/ssl/certs/uaa/tls.crt",
        "key_path": "/etc/ssl/certs/uaa/tls.key",
        "ca_path": "/etc/ssl/certs/uaa/ca.crt"
      },
      "host": "",
      "routes": [
        {
          "name": "uaa",
          "tls_port": 8443,
          "registration_interval": "10s",
          "server_cert_domain_san": "{{ .Values.hostname }}",
          "uris": [
            "{{ .Values.hostname }}",
            "{{ .Values.loginAddress | trimPrefix "https://" }}"
          ]
        }
      ]
    }

